### ISSUE TITLE
ModulenotFoundError

### ISSUE THREAD

**Issue by fenixpapu** [zhangbailong945/mongoengine_adapter#2]
I used:
- ubuntu 20.04. 
- Pycharm pro ( trial)
- create venv and install as your document:
` pip install casbin_mongoengine_adapter`

When I start app I received this message. Can you guys give me some suggestion:

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import casbin_mongoengine_adapter
ModuleNotFoundError: No module named 'casbin_mongoengine_adapter'
```

Update this is output when I check does package installed ?
```
$ python app.py 
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import casbin_mongoengine_adapter
ModuleNotFoundError: No module named 'casbin_mongoengine_adapter'

$ pip install casbin_mongoengine_adapter
Requirement already satisfied: casbin_mongoengine_adapter in ./venv/lib/python3.7/site-packages (0.1.0)
Requirement already satisfied: casbin in ./venv/lib/python3.7/site-packages (from casbin_mongoengine_adapter) (0.16.0)
Requirement already satisfied: mongoengine in ./venv/lib/python3.7/site-packages (from casbin_mongoengine_adapter) (0.22.1)
Requirement already satisfied: simpleeval>=0.9.10 in ./venv/lib/python3.7/site-packages (from casbin->casbin_mongoengine_adapter) (0.9.10)
Requirement already satisfied: pymongo<4.0,>=3.4 in ./venv/lib/python3.7/site-packages (from mongoengine->casbin_mongoengine_adapter) (3.11.3)
```

**Comment by hsluoyz** [comment]
@zhangbailong945

**Comment by fenixpapu** [comment]
Update:
I try with `casbin_sqlalchemy_adapter` it works well with my app.
And this is output when I try `find` command, hope this help:

`casbin_sqlalchemy_adapter`:
```
$ find . | grep casbin_sqlalchemy_adapter
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter/__init__.py
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter/__pycache__
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter/__pycache__/adapter.cpython-37.pyc
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter/__pycache__/__init__.cpython-37.pyc
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter/adapter.py
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter-0.2.0.dist-info
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter-0.2.0.dist-info/top_level.txt
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter-0.2.0.dist-info/WHEEL
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter-0.2.0.dist-info/INSTALLER
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter-0.2.0.dist-info/METADATA
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter-0.2.0.dist-info/LICENSE
./venv/lib/python3.7/site-packages/casbin_sqlalchemy_adapter-0.2.0.dist-info/RECORD

```

And `casbin_mongoengine_adapter`:
```
$ find . | grep casbin_mongoengine_adapter
./venv/lib/python3.7/site-packages/casbin_mongoengine_adapter-0.1.0.dist-info
./venv/lib/python3.7/site-packages/casbin_mongoengine_adapter-0.1.0.dist-info/top_level.txt
./venv/lib/python3.7/site-packages/casbin_mongoengine_adapter-0.1.0.dist-info/WHEEL
./venv/lib/python3.7/site-packages/casbin_mongoengine_adapter-0.1.0.dist-info/INSTALLER
./venv/lib/python3.7/site-packages/casbin_mongoengine_adapter-0.1.0.dist-info/METADATA
./venv/lib/python3.7/site-packages/casbin_mongoengine_adapter-0.1.0.dist-info/LICENSE
./venv/lib/python3.7/site-packages/casbin_mongoengine_adapter-0.1.0.dist-info/RECORD
```

**Comment by Zxilly** [comment]
The author exclude the main package in the pypi package, I have made a PR to fix this.
You should wait the author to merge it. Before that,you can try this.

[casbin_adapter.zip](https://github.com/zhangbailong945/mongoengine_adapter/files/5916945/casbin_adapter.zip)

**Comment by Zxilly** [comment]
Or you can find the correct version in my fork repository

**Comment by fenixpapu** [comment]
Thank for your comments. 
Hope author merge your PR soon. 
I also

**Comment by fenixpapu** [comment]
Thank you! 
I will try to wait author merge your PR.

**Comment by fenixpapu** [comment]
@zhangbailong945
If I copy your `adapter.py` to my project.
It works well. So hopefully you can resolve this issues soon.
Thank in advance.

**Comment by hsluoyz** [comment]
@zhangbailong945 the PR is merged.

Can you give me a maintainer of the PYPI package: https://pypi.org/project/casbin-mongoengine-adapter/ ? So I can release on PYPI? Or you can release it.
